test = {   'name': 'q1a',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> tax_bracket(60000) == 0.22\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> tax_bracket(402150) == 0.24\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> tax_bracket(40125) == 0.12\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> tax_bracket(1) == 0.1\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
