test = {   'name': 'q2a',
    'points': 1,
    'suites': [   {   'cases': [   {'code': ">>> single_number(30) == 'fizz buzz'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> single_number(9) == 'fizz'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> single_number(10) == 'buzz'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> # Make sure you're returning a string, not an int!;\n>>> single_number(1) == '1'\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
