test = {   'name': 'q2b',
    'points': 1,
    'suites': [   {   'cases': [   {'code': ">>> fizz_buzz_sequence(8) == ['1', '2', 'fizz', '4', 'buzz', 'fizz', '7', '8']\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> fizz_buzz_sequence(3) == ['1', '2', 'fizz']\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> fizz_buzz_sequence(15)[14] == 'fizz buzz'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> fizz_buzz_sequence(1000).count('fizz') == 267\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
