test = {   'name': 'q4a',
    'points': 1,
    'suites': [   {   'cases': [   {'code': ">>> is_ing('jogging')\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> not is_ing('ingjog')\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> is_ing('spriNTiNG')\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> not is_ing('racingg')\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
