test = {   'name': 'q2',
    'points': 0,
    'suites': [   {   'cases': [   {   'code': '>>> best_shift_sales([3, 4, 1.25, 6, "Shift Change", 2, 4, 5.75, "Shift Change", 10, 2, .25, "Shift Change"]) == 14.25\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> best_shift_sales([3, 4, 1.25, 6, "Shift Change", 2, 100, 5.75, "Shift Change", 10, 2, .25, "Shift Change"]) == 107.75\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> best_shift_sales([3, 4, 1.25, 6, "Shift Change", 2, 4, 5.75, "Shift Change", 10, 2, 100.25, "Shift Change"]) == 112.25\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
