test = {   'name': 'q4c',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> # This test makes sure basel_arr has the correct number of elements.;\n>>> len(basel_arr) == 10**7\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> # This test makes sure the values in basel_arr are correct.;\n>>> np.isclose(basel_arr[45], 0.0004725897920604915)\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> # This test makes sure the values in basel_arr are correct.;\n>>> np.isclose(basel_arr[-1], 0)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> # This test makes sure basel_sum_arr is correct.;\n>>> np.isclose(basel_sum_arr, 1.6449339668482332)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
