test = {   'name': 'q1f-part1',
    'points': 2,
    'suites': [   {   'cases': [   {'code': ">>> str_to_cat('21.8%') == 'rapid increase'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> str_to_cat('4.8%') == 'steady increase'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> str_to_cat('-1.1%') == 'stagnant'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> str_to_cat('-8.8%') == 'steady decrease'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> str_to_cat('-19.9%') == 'rapid decrease'\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
