test = {   'name': 'q1c',
    'points': 1,
    'suites': [   {   'cases': [   {'code': ">>> eight_type in ['int', 'float', 'str', 'bool', 'NoneType']\nTrue", 'hidden': False, 'locked': False},
                                   {   'code': ">>> # If you see this error, don't just copy the correct answer – think about why it's correct!;\n>>> eight_type == 'NoneType'\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
