test = {   'name': 'q2a',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(biden_height_m, float)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(biden_height_m, 1.8034)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> isinstance(biden_mass_kg, float)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(biden_mass_kg, 80.9091)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
