test = {   'name': 'q2d',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> not is_extreme(biden_height_in, biden_weight_lb)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> is_extreme(100, 15)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> is_extreme(15, 1000)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> not is_extreme(72, 200)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
