test = {   'name': 'q4c',
    'points': 1,
    'suites': [   {   'cases': [   {'code': ">>> is_valid_november_2020_sweden('Sweden', '2020-11-04')\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> not is_valid_november_2020_sweden('sweden', '2020-11-04')\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> not is_valid_november_2020_sweden('Sweden', '2020-11-302')\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> not is_valid_november_2020_sweden('Sweden', '2019-11-24')\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
