test = {   'name': 'q1a-code',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> np.isclose(sphere_volume_fixed(5), 523.59833)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(sphere_volume_fixed(15), 14137.155)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(sphere_volume_fixed(0.1), 0.004188766)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(sphere_volume_fixed(-2), 0)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
