test = {   'name': 'q1b',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> quadratic_equation_fixed(1, 5, 4) == [-1.0, -4.0]\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> quadratic_equation_fixed(2, -9, 4) == [4.0, 0.5]\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> quadratic_equation_fixed(1, -10, 25) == [5.0]\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> quadratic_equation_fixed(1, 5, 16) == False\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
