test = {   'name': 'q1c-code',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> sum_digits_fixed(4) == 4\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sum_digits_fixed(519) == 15\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sum_digits_fixed(123456) == 21\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sum_digits_fixed(21203) == 8\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
