test = {   'name': 'q1d',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> is_510_fixed(5106421000)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> is_510_fixed(5109697912)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> not is_510_fixed(510666)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> not is_510_fixed(2488129195)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
