test = {   'name': 'q2a',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> sum_first_n_squares(3) == 14\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sum_first_n_squares(10) == 385\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sum_first_n_squares(15) == 1240\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sum_first_n_squares(1000) == 333833500\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
