test = {   'name': 'q2c',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> alternating_product([2, 8.5, 1, 9]) == 2\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> alternating_product([2, 8.5, 1, 9, 4.5]) == 9.0\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> alternating_product([1, 2, 3, 4, 5, 9, -22]) == -330\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> alternating_product([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) == 945\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
