test = {   'name': 'q4',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> one_streak([13, 3, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 2, 5, 7, 8]) == 9\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> one_streak([4, 1, 1, 1, 2, 3, 11, 1, 1, 1, 1, 1]) == 5\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> one_streak([5, 4, 1, 1, 1, 3, 2, 1, 2, 3]) == 3\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> one_streak([1, 2, 3, 4, 5]) == 1\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
